spring:
  application:
    name: service-customer
  profiles:
      active: dev
  cloud:
    config:
      uri: ${GIT_URL:http://localhost:9000/}
      failFast: false
      # discovery:
      #   enabled: true
      #   serviceId: service-config
  datasource:
    url: jdbc:mysql://172.19.1.110:3306/demo
    username: root
    password: fangang12321
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapperLocations: classpath:mapper/*Mapper.xml
feign:
  hystrix:
    enabled: true
logging:
  level:
    org.easydev.customer: debug
    
---
spring:
  profiles: dev
  sleuth:
    enabled: false
server:
  port: 9002

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
---
spring:
  profiles: docker

server:
  port: ${SERVICE_PORT:9002}

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${REGISTRY_URL}